### ISSUE TITLE
Some problems about the datasets Insta-NY & Insta-LA

### ISSUE THREAD

**Issue by Gemini126** [MinChen00/UnlearningLeaks#6]
Sorry to bother you, I've checked the paper ,related paper and the code thoroughly,but I can't really understand how & where I can get these two datasets.While the dataset is collected from the Instagram API and Four Square API,I only get an invalid page now.Could you provide the URL of the dataset if you have or other methods through which I can download these datasets? Thanks a lot.

**Comment by Milkigit** [comment]
Sorry, the original dataset is not downloaded by me. I only have the preprocessed version, which can be found at https://drive.google.com/drive/folders/1A7iBRWvIIeUY8UA2Pc8we-fpKaWuA3Hx.
